### ISSUE TITLE
RtpTransport should be called RTCRtpTransport

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-rtptransport#2]
I assume, as per all our other RTC-interfaces.

**Comment by tonyherre** [comment]
Can decide this now? Consistency would say it should be **RTC**RtpTransport, but I'm not sure what else it gains us to overcome the extra characters (and inconsistent capitalization, and difficulty reading the name...).
Why were our other RTP APIs prefixed as such?

@alvestrand @aboba @pthatcher @Philipel-WebRTC @Orphis et al

**Comment by tonyherre** [comment]
Thanks Harald!
In that case, I'd suggest the "Rtp" prefix is enough namespacing for the types in this spec, so we would be fine without "RTC". There'll be a modicum of inconsistency, but devs are used to using things which aren't RTC... in WebRTC apps, with things such core things as MediaStreamTracks etc.

Anyone feel strongly in the other direction?

**Comment by dontcallmedom** [comment]
the [naming conventions](https://w3ctag.github.io/design-principles/#casing-rules) would suggest making it upper case through (i.e. `RTP` as a prefix)

**Comment by tonyherre** [comment]
In fact applying the "Repeated initialisms in APIs" convention there, we would be choosing between `RTCRTPTransport` and `RTPTransport`...

**Comment by tonyherre** [comment]
RTCRtpTransport sounds good to me!

**Comment by pthatcher** [comment]
Then we also need RTCRtpSendStream, RTCRtpReceiveStream, yada yada
