### ISSUE TITLE
Unsignalled streams aren't needed by any existing usecase

### ISSUE THREAD

**Issue by tonyherre** [w3c/webrtc-rtptransport#66]
As discussed in last week's discussion meeting, we've had a way to add unsignalled/negotiated RTCRtpSendStreams/RTCRtpReceiveStreams via the `RTCRtpTransport. addRtpSendStream()` and `RTCRtpTransport. addRtpReceiveStream()` methods for quite a while, but none of the existing usecases actually need them. Everything we have can be conducted by first adding a transceiver and negotiating:

```
let t = pc.addTransceiver('video');
await negotiate(); // Custom stuff, using custom codec negotiation API if required
let sendStream = await t.sender.replaceSendStream();
```

I suggest we delete the add methods until we have a fleshed out usecase that needs such unsignalled streams and works out the corner cases.

**Comment by alvestrand** [comment]
Unsignalled streams were added to the implementation to allow interoperation with RTP speakers that did not support the MID extension. Since these also did not support BUNDLE, the need to support these devices seems to be rather low.

I support deleting them.

**Comment by alvestrand** [comment]
For custom RTP header extensions, we need to "just" remove the rule that requires perfect match between the argument to setHeaderExtensionsToNegotiate and the previous value of [[HeaderExtensionsToNegotiate]].

**Comment by aboba** [comment]
@pthatcher said: 

"The motivation for this is that one can use RtpTransport without using SDP adding/removing streams. While we don't have anything in the explainers, I feel like we could easily add examples to them to "motivate" these methods, and I'd rather do that than remove these."

Use Case 1 should probably do a better job covering custom codecs.

**Comment by alvestrand** [comment]
I feel like Add*Stream methods belong in the spec, but as part of adding the capability to configure the PeerConnection without an SDP exchange.
The ICE APIs currently in progress should allow us to get candidates added without SDP; cert.getFingerprints() can get us the necessary credit for DTLS setup; there's probably more I've missed (but I don't think it's that much).

The Bad Thing about adding Add*Stream methods is that specifying the relationship between Add*Stream and renegotiation using SDP is *hard*, and a kluge that we'd not want to maintain once we have SDP-less RtpTransport.

**Comment by pthatcher** [comment]
There are two parts to "SDP-less PeerConnection": 1. initial setup and 2. changes after the initial setup.    In my experience, it would be great to allow is to avoid SDP for both, but by far most of the pain is in #2, and most of that pain is in adding and removing RTP streams for things like video conferences.  I think having these methods in RtpTransport would gives us one of those "reduce 80% of the pain with only 20% of the effort" type of pay offs.

I don't think specifying the relationship between Add*Stream and SDP renegotiation needs to be hard if we allow ourselves to make a simple rule like "streams created by Add*Stream are bound by the guard rails of SDP".
